"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XiHlSRTCFwN6EFR6xzlOH__buG5_OvXv

"""

import random
import string
import numpy as np


from google.colab import drive
drive.mount('/content/drive')

# !ls -l /content/drive/MyDrive/ps2/

path = "/content/drive/MyDrive/MIT_python/ps2/"
WORDLIST_FILENAME = path + "words.txt"

def load_words():
    """
    Returns a list of valid words. Words are strings of lowercase letters.

    Depending on the size of the word list, this function may
    take a while to finish.
    """
    print("Loading word list from file...")
    # inFile: file
    inFile = open(WORDLIST_FILENAME, 'r')
    # line: string
    line = inFile.readline()
    # wordlist: list of strings
    wordlist = line.split()
    print("  ", len(wordlist), "words loaded.")
    return wordlist


def choose_word(wordlist):
    """
    wordlist (list): list of words (strings)

    Returns a word from wordlist at random
    """
    return random.choice(wordlist)

# end of helper code

# -----------------------------------

# Load the list of words into the variable wordlist
# so that it can be accessed from anywhere in the program
wordlist = load_words()

def is_word_guessed(secret_word, letters_guessed):
    '''
    secret_word: string, the word the user is guessing; assumes all letters are
      lowercase
    letters_guessed: list (of letters), which letters have been guessed so far;
      assumes that all letters are lowercase
    returns: boolean, True if all the letters of secret_word are in letters_guessed;
      False otherwise
    '''


    for l in secret_word:
      if l in letters_guessed:
        pass
      else:
        return False

    return True

def get_guessed_word(secret_word, letters_guessed):
    '''
    secret_word: string, the word the user is guessing
    letters_guessed: list (of letters), which letters have been guessed so far
    returns: string, comprised of letters, underscores (_), and spaces that represents
      which letters in secret_word have been guessed so far.
    '''

    st = ''
    for l in secret_word:
      if l in letters_guessed:
        st = st + l + ' '
      else:
        st = st + '_' + ' '
    return st

def get_available_letters(letters_guessed):
    '''
    letters_guessed: list (of letters), which letters have been guessed so far
    returns: string (of letters), comprised of letters that represents which letters have not
      yet been guessed.
    '''

    all_letters = string.ascii_lowercase

    req_st = ''.join([s for s in all_letters if s not in letters_guessed])

    return req_st

def lose_warning(n_warning,i, secret_word, letters_guessed):
  if n_warning>0:
    n_warning = n_warning - 1
    guess = get_guessed_word(secret_word, letters_guessed)
  else:
    i= i+1
    print("No more warning. Losing 1 guess")
  return n_warning, i

def hangman(secret_word, nguess = 6, n_warning = 3):
    '''
    secret_word: string, the secret word to guess.

    Starts up an interactive game of Hangman.

    * At the start of the game, let the user know how many
      letters the secret_word contains and how many guesses s/he starts with.

    * The user should start with 6 guesses

    * Before each round, you should display to the user how many guesses
      s/he has left and the letters that the user has not yet guessed.

    * Ask the user to supply one guess per round. Remember to make
      sure that the user puts in a letter!

    * The user should receive feedback immediately after each guess
      about whether their guess appears in the computer's word.

    * After each guess, you should display to the user the
      partially guessed word so far.

    Follows the other limitations detailed in the problem write-up.
    '''


    # print(secret_word)
    # print("")

    print("\nWelcome to the game Hangman!!")
    print("")

    print("The secret word contains", len(secret_word), "letters.")
    print("Number of guesses allowed", nguess)
    print("Number of warnings", n_warning)
    print("------------------------------------------------------")


    letters_guessed = []
    i = 1

    while i <= nguess:
        print(i, nguess)

        # Print number of guesses and available letters.
        print("\nYou have", nguess-i+1, "guesses left.\n")
        available_letters = get_available_letters(letters_guessed)
        print("The available letters are: ", available_letters)

        # Guess letter
        l_guess = input("Guess a letter:")
        # Check if input is an alphabet. If not alphabet warning reduces by 1.
        if str.isalpha(l_guess):
            # Make sure the letter is lowercase.
            l_guess = str.lower(l_guess)
            # Check if already guessed same letter. Lose warning if already guessed until warnings last then lose a guess.
            if l_guess in letters_guessed:
                n_warning, i = lose_warning(n_warning, i, secret_word, letters_guessed)
                print(l_guess, "already guessed before.", n_warning, "warnings left:")
                print("-----------------------------------")
            else:
                letters_guessed.append(l_guess)
                # Check if letter guessed is in secret word.
                if l_guess in secret_word:
                    guess = get_guessed_word(secret_word, letters_guessed)
                    print("Good guess:", guess)
                    print("-----------------------------------")
                # For letter guessed not in secret word.
                else:
                    all_letters = string.ascii_lowercase
                    vowels = ['a', 'e', 'i', 'o', 'u']
                    consonants = [i for i in all_letters if i not in vowels]
                    # If a vowel lose two guesses.
                    if l_guess in vowels:
                        i = i+2
                    # If consonant lose only one guess.
                    elif l_guess in consonants:
                        i = i+1
                    guess = get_guessed_word(secret_word, letters_guessed)
                    print("Oops! Letter not in secret word. Try again.", guess)
                    print("-----------------------------------")

        # If not alphabet warning reduces by 1 until available and then lose a guess.
        else:
            n_warning,i = lose_warning(n_warning, i, secret_word, letters_guessed)
            print("Invalid input. Enter only alphabets.", n_warning, "warnings left:", guess)
            print("-----------------------------------")


        #Check if the word is guessed:
        if is_word_guessed(secret_word, letters_guessed):
            #Total score = guesses_remaining* number unique letters in secret_word
            guess_left = nguess-i+1
            n_unique = np.unique(np.array(list(secret_word)))
            score = guess_left * len(n_unique)
            print("Congratulations, you won!")
            print("Your final score is", score)
            break


    # If all nguesses are over and word not yet correctly guessed, the game is lost.
    if i > nguess:
        print("\nSorry, you lost the game.")
        print("The secret word is", secret_word)

    pass

# When you've completed your hangman_with_hint function, comment the two similar
# lines above that were used to run the hangman function, and then uncomment
# these two lines and run this file to test!
# Hint: You might want to pick your own secret_word while you're testing.


if __name__ == "__main__":

    # secret_word = input('Enter the secret word')
    # hangman(secret_word)

    # To test part 2, comment out the pass line above and
    # uncomment the following two lines.

    wordlist = load_words()
    secret_word = choose_word(wordlist)
    hangman(secret_word)

    pass



###############

7# When you've completed your hangman function, scroll down to the bottom
# of the file and uncomment the first two lines to test
#(hint: you might want to pick your own
# secret_word while you're doing your own testing)


# -----------------------------------



def match_with_gaps(my_word, other_word):
    '''
    my_word: string with _ characters, current guess of secret word
    other_word: string, regular English word
    returns: boolean, True if all the actual letters of my_word match the
        corresponding letters of other_word, or the letter is the special symbol
        _ , and my_word and other_word are of the same length;
        False otherwise:
    '''

    my_chrs = [l for l in list(my_word) if l != ' ']

    # matches = 0
    # for i in range(len(my_word)):
    #   if my_word[i] == list(other_word)[i] or my_word[i] == '_':
    #     matches += 1

    # if matches == len(my_word):
    #   return True

    # else:
    #   return False
    if len(my_chrs) == len(other_word):
        matches = [i for i in range(len(my_chrs)) if my_chrs[i] == list(other_word)[i] or my_chrs[i] == '_']
        if len(my_chrs) == len(matches):
            #print('Found a match.')
            return True
    else:
        return False

def show_possible_matches(my_word):
    '''
    my_word: string with _ characters, current guess of secret word
    returns: nothing, but should print out every word in wordlist that matches my_word
             Keep in mind that in hangman when a letter is guessed, all the positions
             at which that letter occurs in the secret word are revealed.
             Therefore, the hidden letter(_ ) cannot be one of the letters in the word
             that has already been revealed.

    '''

    print("\nShowing possible matching words.")
    print("")

    all_matches = [other_word for other_word in wordlist if match_with_gaps(my_word, other_word)]

    req_word = ''.join([l for l in list(my_word) if l != ' '])
    # missing letter positions
    missing_index = [i for i, chr in enumerate(list(req_word)) if chr == '_']

    all_posible_match = []
    for i, word in enumerate(all_matches):
        missing_letters = np.array(list(word))[missing_index]
        # for l in missing_letters:
        #   if l in list(my_word):
        #      break
        #   else:
        #       pass
        # all_posible_match.append(word)

        if set(missing_letters).isdisjoint(set(list(req_word))):
            print(word)
            all_posible_match.append(word)



############################################



def hangman_with_hints(secret_word, nguess=6, n_warning=3):
    '''
    secret_word: string, the secret word to guess.

    Starts up an interactive game of Hangman.

    * At the start of the game, let the user know how many
      letters the secret_word contains and how many guesses s/he starts with.

    * The user should start with 6 guesses

    * Before each round, you should display to the user how many guesses
      s/he has left and the letters that the user has not yet guessed.

    * Ask the user to supply one guess per round. Make sure to check that the user guesses a letter

    * The user should receive feedback immediately after each guess
      about whether their guess appears in the computer's word.

    * After each guess, you should display to the user the
      partially guessed word so far.

    * If the guess is the symbol *, print out all words in wordlist that
      matches the current guessed word.

    Follows the other limitations detailed in the problem write-up.
    '''

    # print(secret_word)
    # print("")

    print("\nWelcome to the game Hangman!!")
    print("")

    print("The secret word contains", len(secret_word), "letters.")
    print("Number of guesses allowed", nguess)
    print("Number of warnings", n_warning)
    print("------------------------------------------------------")


    letters_guessed = []
    i = 1

    while i <= nguess:
        print(i, nguess)

        if is_word_guessed(secret_word, letters_guessed):
            #Total score = guesses_remaining* number unique letters in secret_word
            guess_left = nguess-i+1
            n_unique = np.unique(np.array(list(secret_word)))
            score = guess_left * len(n_unique)
            print("Congratulations, you won!")
            print("Your final score is", score)
            break

        # Print number of guesses and available letters.
        print("\nYou have", nguess-i+1, "guesses left.\n")
        available_letters = get_available_letters(letters_guessed)
        print("The available letters are: ", available_letters)

        # Guess letter
        l_guess = input("Guess a letter:")

        # Check if input is an alphabet.
        if str.isalpha(l_guess):
            # Make sure the letter is lowercase.
            l_guess = str.lower(l_guess)
            # Check if already guessed same letter.
            if l_guess in letters_guessed:
                n_warning, i = lose_warning(n_warning, i)
                print(l_guess, "already guessed before.", n_warning, "warnings left:")
                print("-----------------------------------")

            else:
                letters_guessed.append(l_guess)
                # Check if letter guessed is in secret word.
                if l_guess in secret_word:
                    guess = get_guessed_word(secret_word, letters_guessed)
                    print("Good guess:", guess)
                    print("-----------------------------------")
                # For letter guessed not in secret word.
                else:
                    all_letters = string.ascii_lowercase
                    vowels = ['a', 'e', 'i', 'o', 'u']
                    consonants = [i for i in all_letters if i not in vowels]
                    # Check if vowel.
                    if l_guess in vowels:
                      i = i+2
                    # If constant.
                    elif l_guess in consonants:
                        i = i+1
                    guess = get_guessed_word(secret_word, letters_guessed)
                    print("Oops! Letter not in secret word. Try again.", guess)
                    print("-----------------------------------")


        # Hints: Show possible matching words.
        elif l_guess == '*':
            print("Asked for hints.")
            show_possible_matches(guess)

        else:
            # If not alphabet or '*' warning reduces by 1.
            n_warning,i = lose_warning(n_warning, i)
            print("Invalid input. Enter only alphabets.", n_warning, "warnings left:", guess)
            print("-----------------------------------")

        if i > nguess:
            print("\nSorry, you lost the game.")
            print("The secret word is", secret_word)

    pass

# To test part 3 re-comment out the above lines and
# uncomment the following two lines.

secret_word = choose_word(wordlist)
hangman_with_hints(secret_word)



# # Trial code

# wordlist = load_words()
# secret_word = choose_word(wordlist)
# # print(secret_word)
# # print()

# print("\nWelcome to the game Hangman!!")
# print("")

# nguess= len(secret_word)+2
# n_warning = 3
# print("The secret word contains", len(secret_word), "letters.")
# print("Number of guesses allowed", nguess)
# print("Number of warnings", n_warning)
# print("------------------------------------------------------")


# letters_guessed = []
# i = 1

# while i <= nguess:
#   print(i,nguess)

#   # Check if word already guessed:
#   secret_word_srt = ''.join(sorted(secret_word, key=str.lower))
#   guess_word_srt  = ''.join(sorted(letters_guessed, key=str.lower))

#   if secret_word_srt == guess_word_srt:
#     guess = get_guessed_word(secret_word, letters_guessed)
#     print("Word guessed correctly!")
#     break

#   # Print number of guesses and available letters.
#   print("\nYou have", nguess-(i-1), "guesses left.\n")
#   available_letters = get_available_letters(letters_guessed)
#   print("The available letters are: ", available_letters)

#   # Guess letter
#   l_guess = input("Guess a letter:")
#   if not str.isalpha(l_guess):
#     n_warning = n_warning - 1
#     if n_warning>=0:
#       guess = get_guessed_word(secret_word, letters_guessed)
#       print("Invalid input. Enter only alphabets.", n_warning, "warnings left:", guess)
#       print("-----------------------------------")
#     else:
#       i= i+1
#       print("Warnings exhausted")
#       print("Losing 1 guess")
#   else:
#     l_guess = str.lower(l_guess)
#     if l_guess in secret_word:
#       letters_guessed.append(l_guess)
#       guess = get_guessed_word(secret_word, letters_guessed)
#       print("Good guess:", guess)
#       i = i+1
#       print("-----------------------------------")
#     else:
#       guess = get_guessed_word(secret_word, letters_guessed)
#       i = i+1
#       print("Oops! Try again.", guess)
#       print("-----------------------------------")

#Problem 3 Part 2 D:

wordlist = load_words()
secret_word = choose_word(wordlist)
print(secret_word)
print()

print("\nWelcome to the game Hangman!!")
print("")

nguess= len(secret_word)+2
n_warning = 3
print("The secret word contains", len(secret_word), "letters.")
print("Number of guesses allowed", nguess)
print("Number of warnings", n_warning)
print("------------------------------------------------------")


letters_guessed = []
i = 1

while i <= nguess:
  print(i, nguess)

  # Check if word already guessed:
  # secret_word_srt = ''.join(sorted(secret_word, key=str.lower))
  # guess_word_srt  = ''.join(sorted(letters_guessed, key=str.lower))

  # if secret_word_srt == guess_word_srt:
  if is_word_guessed:
    print("Congratulations, you won!")
    break

  # Print number of guesses and available letters.
  print("\nYou have", nguess-i+1, "guesses left.\n")
  available_letters = get_available_letters(letters_guessed)
  print("The available letters are: ", available_letters)

  # Guess letter
  l_guess = input("Guess a letter:")
  # Check if input is an alphabet. If not alphabet warning reduces by 1.
  if str.isalpha(l_guess):
    # Make sure the letter is lowercase.
    l_guess = str.lower(l_guess)
    # Check if already guessed same letter.
    if l_guess in letters_guessed:
      n_warning, i = lose_warning(n_warning, i)
      print(l_guess, "already guessed before.", n_warning, "warnings left:")
      print("-----------------------------------")

    else:
      letters_guessed.append(l_guess)
      # Check if letter guessed is in secret word.
      if l_guess in secret_word:
        guess = get_guessed_word(secret_word, letters_guessed)
        print("Good guess:", guess)
        print("-----------------------------------")
      # For letter guessed not in secret word.
      else:
        all_letters = string.ascii_lowercase
        vowels = ['a', 'e', 'i', 'o', 'u']
        consonants = [i for i in all_letters if i not in vowels]
        # Check if vowel.
        if l_guess in vowels:
          i = i+2
        elif l_guess in consonants:
          i = i+1
        guess = get_guessed_word(secret_word, letters_guessed)
        print("Oops! Letter not in secret word. Try again.", guess)
        print("-----------------------------------")

  else:

    # If not alphabet warning reduces by 1.
    n_warning,i = lose_warning(n_warning, i)
    print("Invalid input. Enter only alphabets.", n_warning, "warnings left:", guess)
    print("-----------------------------------")



if i > nguess:
  print("\nSorry, you lost the game.")
  print("The secret word is", secret_word)

#Problem 3 Part 2 E:


# wordlist = load_words()
# secret_word = choose_word(wordlist)
secret_word = 'apple'
print(secret_word)
print()

print("\nWelcome to the game Hangman!!")
print("")

nguess= len(secret_word)+2
n_warning = 3
print("The secret word contains", len(secret_word), "letters.")
print("Number of guesses allowed", nguess)
print("Number of warnings", n_warning)
print("------------------------------------------------------")


letters_guessed = []
i = 1

while i <= nguess:
  print(i, nguess)

  # Check if word already guessed:
  # secret_word_srt = ''.join(sorted(secret_word, key=str.lower))
  # guess = get_guessed_word(secret_word, letters_guessed)
  # guess_word_srt  = ''.join(sorted(guess, key=str.lower))

  # print('secret word',secret_word_srt, 'guess', guess_word_srt)
  if is_word_guessed(secret_word, letters_guessed):
    #Total score = guesses_remaining* number unique letters in secret_word
    guess_left = nguess-i+1
    n_unique = np.unique(np.array(list(secret_word)))
    score = guess_left * len(n_unique)
    print("Congratulations, you won!")
    print("Your final score is", score)
    break


  # Print number of guesses and available letters.
  print("\nYou have", nguess-i+1, "guesses left.\n")
  available_letters = get_available_letters(letters_guessed)
  print("The available letters are: ", available_letters)

  # Guess letter
  l_guess = input("Guess a letter:")
  # Check if input is an alphabet. If not alphabet warning reduces by 1.
  if str.isalpha(l_guess):
    # Make sure the letter is lowercase.
    l_guess = str.lower(l_guess)
    # Check if already guessed same letter.
    if l_guess in letters_guessed:
      n_warning, i = lose_warning(n_warning, i)
      print(l_guess, "already guessed before.", n_warning, "warnings left:")
      print("-----------------------------------")

    else:
      letters_guessed.append(l_guess)
      # Check if letter guessed is in secret word.
      if l_guess in secret_word:
        guess = get_guessed_word(secret_word, letters_guessed)
        print("Good guess:", guess)
        print("-----------------------------------")
      # For letter guessed not in secret word.
      else:
        all_letters = string.ascii_lowercase
        vowels = ['a', 'e', 'i', 'o', 'u']
        consonants = [i for i in all_letters if i not in vowels]
        # Check if vowel.
        if l_guess in vowels:
          i = i+2
        # If constant.
        elif l_guess in consonants:
          i = i+1
        guess = get_guessed_word(secret_word, letters_guessed)
        print("Oops! Letter not in secret word. Try again.", guess)
        print("-----------------------------------")

  else:
    # If not alphabet warning reduces by 1.
    n_warning,i = lose_warning(n_warning, i)
    print("Invalid input. Enter only alphabets.", n_warning, "warnings left:", guess)
    print("-----------------------------------")



if i > nguess:
  print("\nSorry, you lost the game.")
  print("The secret word is", secret_word)